FROM rust:1.54.0 AS builder
WORKDIR /app
COPY . .
ENV SQLX_OFFLINE true
RUN cargo build --release

FROM debian:buster-slim AS runtime
WORKDIR /app
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/showsk_rs showsk-rs
COPY conf conf
COPY static/css static/css
ENV APP_ENVIRONMENT production
ENTRYPOINT ["./showsk-rs"]
